export function wellKnownMcp() {
  return {
    name: "syenite",
    version: "0.5.1",
    description:
      "The DeFi interface for AI agents — swap and bridge (30+ chains), yield and lending, prediction markets and signals, carry and strategy search, position alerts, wallet and gas, and a trust layer (tx.verify, tx.simulate, tx.guard) for verification before signing. MCP.",
    transport: "streamable-http",
    endpoint: "/mcp",
    authentication: "none",
    tools: [
      "syenite.help",
      "wallet.balances",
      "gas.estimate",
      "swap.quote",
      "swap.multi",
      "swap.status",
      "tx.verify",
      "tx.simulate",
      "tx.guard",
      "yield.opportunities",
      "yield.assess",
      "lending.rates.query",
      "lending.market.overview",
      "lending.position.monitor",
      "lending.risk.assess",
      "strategy.carry.screen",
      "find.strategy",
      "prediction.trending",
      "prediction.search",
      "prediction.book",
      "prediction.signals",
      "alerts.watch",
      "alerts.check",
      "alerts.list",
      "alerts.remove",
    ],
    rateLimit: {
      requestsPerMinute: 30,
      basis: "IP address",
    },
  };
}
