export function wellKnownMcp() {
  return {
    name: "syenite",
    version: "0.6.0",
    description:
      "Real-time lending rates (Aave, Morpho, Compound, Spark) and yield opportunities — with position alerts and webhooks. Swap and bridge routing (30+ chains), lending execution, prediction markets, carry screening, wallet and gas, and a trust layer (tx.verify, tx.simulate, tx.guard, tx.receipt). DeFi MCP for AI agents.",
    transport: "streamable-http",
    endpoint: "/mcp",
    authentication: "none",
    tools: [
      "syenite.help",
      "wallet.balances",
      "gas.estimate",
      "swap.quote",
      "swap.multi",
      "swap.status",
      "tx.verify",
      "tx.simulate",
      "tx.guard",
      "tx.receipt",
      "yield.opportunities",
      "yield.assess",
      "lending.rates.query",
      "lending.market.overview",
      "lending.position.monitor",
      "lending.risk.assess",
      "lending.supply",
      "lending.borrow",
      "lending.withdraw",
      "lending.repay",
      "strategy.carry.screen",
      "find.strategy",
      "prediction.trending",
      "prediction.search",
      "prediction.book",
      "prediction.signals",
      "alerts.watch",
      "alerts.check",
      "alerts.list",
      "alerts.remove",
      "metamorpho.supply",
      "metamorpho.withdraw",
      "token.price",
      "prediction.market",
      "prediction.watch",
      "prediction.position",
      "prediction.quote",
      "prediction.order",
    ],
    rateLimit: {
      requestsPerMinute: 30,
      basis: "IP address",
    },
  };
}
